# Form implementation generated from reading ui file 'c:\Users\qpmch\Documents\Code Repositories\Personal\readwise-anki-gpt\src\readwise-anki-gpt\designer\readwise_anki_gpt.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReadwiseAnkiGPT(object):
    def setupUi(self, ReadwiseAnkiGPT):
        ReadwiseAnkiGPT.setObjectName("ReadwiseAnkiGPT")
        ReadwiseAnkiGPT.resize(494, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReadwiseAnkiGPT)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windowTitle = QtWidgets.QLabel(parent=ReadwiseAnkiGPT)
        self.windowTitle.setObjectName("windowTitle")
        self.verticalLayout.addWidget(self.windowTitle)
        self.instructionsLabel = QtWidgets.QLabel(parent=ReadwiseAnkiGPT)
        self.instructionsLabel.setObjectName("instructionsLabel")
        self.verticalLayout.addWidget(self.instructionsLabel)
        self.readwiseImportHighlightsButton = QtWidgets.QPushButton(parent=ReadwiseAnkiGPT)
        self.readwiseImportHighlightsButton.setObjectName("readwiseImportHighlightsButton")
        self.verticalLayout.addWidget(self.readwiseImportHighlightsButton)
        self.instructionsLabel2 = QtWidgets.QLabel(parent=ReadwiseAnkiGPT)
        self.instructionsLabel2.setWordWrap(True)
        self.instructionsLabel2.setObjectName("instructionsLabel2")
        self.verticalLayout.addWidget(self.instructionsLabel2)
        self.readwiseHighlightTreeView = QtWidgets.QTreeView(parent=ReadwiseAnkiGPT)
        self.readwiseHighlightTreeView.setObjectName("readwiseHighlightTreeView")
        self.verticalLayout.addWidget(self.readwiseHighlightTreeView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generateCardButton = QtWidgets.QPushButton(parent=ReadwiseAnkiGPT)
        self.generateCardButton.setObjectName("generateCardButton")
        self.horizontalLayout.addWidget(self.generateCardButton)
        self.editCardButton = QtWidgets.QPushButton(parent=ReadwiseAnkiGPT)
        self.editCardButton.setObjectName("editCardButton")
        self.horizontalLayout.addWidget(self.editCardButton)
        self.deleteCardButton = QtWidgets.QPushButton(parent=ReadwiseAnkiGPT)
        self.deleteCardButton.setObjectName("deleteCardButton")
        self.horizontalLayout.addWidget(self.deleteCardButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ReadwiseAnkiGPT)
        QtCore.QMetaObject.connectSlotsByName(ReadwiseAnkiGPT)

    def retranslateUi(self, ReadwiseAnkiGPT):
        _translate = QtCore.QCoreApplication.translate
        ReadwiseAnkiGPT.setWindowTitle(_translate("ReadwiseAnkiGPT", "Readwise Anki GPT"))
        self.windowTitle.setText(_translate("ReadwiseAnkiGPT", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Readwise Anki GPT</span></p></body></html>"))
        self.instructionsLabel.setText(_translate("ReadwiseAnkiGPT", "First, import your highlights from Readwise:"))
        self.readwiseImportHighlightsButton.setText(_translate("ReadwiseAnkiGPT", "Import Highlights from Readwise"))
        self.instructionsLabel2.setText(_translate("ReadwiseAnkiGPT", "Then, select Readwise highlight(s) below and use the buttons below to generate, edit, or delete Anki cards."))
        self.generateCardButton.setText(_translate("ReadwiseAnkiGPT", "Generate Card"))
        self.editCardButton.setText(_translate("ReadwiseAnkiGPT", "Edit Card"))
        self.deleteCardButton.setText(_translate("ReadwiseAnkiGPT", "Delete Card"))
